version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: geofencing_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: geofencing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d geofencing"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: geofencing_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/geofencing?sslmode=disable
      - MIGRATION=true
      - JWT_SECRET=Vikash0277
      - GOOGLE_CLIENT_ID=1082271042683-g2cvr5s6d8i32ddu0pu0149dbaa63bb1.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_REDIRECT_URL=http://localhost:3001/api/v1/auth/google/callback
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
